FROM node:22-alpine

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

# ARG DATABASE_URL
# ENV DATABASE_URL=$DATABASE_URL
RUN npx prisma db pull
RUN npx prisma generate

CMD ["node", "server.js"]